<a href="https://colab.research.google.com/github/PolinaBoeva/predictive_models_dota2/blob/models/experiments/Boeva/%D1%87%D0%B5%D0%BA%D0%BF%D0%BE%D0%B8%D0%BD%D1%82_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import make_scorer
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore")

In [ ]:
y_train = pd.read_csv('y_train.csv', index_col=0)
X_train = pd.read_csv('X_train.csv', index_col=0)
X_test = pd.read_csv('X_test.csv', index_col=0)
y_test = pd.read_csv('y_test.csv', index_col=0)

In [ ]:
y_train_heroes = pd.read_csv('y_train_heroes.csv', index_col=0)
X_train_heroes = pd.read_csv('X_train_heroes.csv', index_col=0)
X_test_heroes = pd.read_csv('X_test_heroes.csv', index_col=0)
y_test_heroes = pd.read_csv('y_test_heroes.csv', index_col=0)

In [ ]:
metrics_df = pd.DataFrame(columns=["Model", "Accuracy", "Precision", "Recall", "F1 Score", "ROC-AUC"])

In [ ]:
def get_model_metrics(y_test, predictions, X_test,  model_name, predict_proba=None):
    global metrics_df
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions)
    recall = recall_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)
    if predict_proba:
        roc_auc = roc_auc_score(y_test, predict_proba(X_test)[:, 1])  # Для AUC-ROC используем predict_proba
    else:
        roc_auc = "N/A"
    print(f"Metrics for {model_name}:")
    print(f"Accuracy: {round(accuracy, 3)}")
    print(f"Precision: {round(precision, 3)}")
    print(f"Recall: {round(recall, 3)}")
    print(f"F1 Score: {round(f1, 3)}")
    print(f"ROC-AUC: {round(roc_auc, 3)}")

    new_metrics = pd.DataFrame([[model_name, round(accuracy, 3), round(precision, 3),
                                 round(recall, 3), round(f1, 3), round(roc_auc, 3)]],
                                columns=metrics_df.columns)

    metrics_df = pd.concat([metrics_df, new_metrics], ignore_index=True)

# Модели логистической регрессии

In [ ]:
# Бейзлайн модель. Увеличила количество интераций для сходимости
pipeline = Pipeline([
    ('scaler_', StandardScaler()),
    ('model_', LogisticRegression(max_iter=500))
])

# Обучение пайплайна
pipeline.fit(X_train, y_train)

# Прогнозирование на тестовой выборке
predictions = pipeline.predict(X_test)
predict_proba = pipeline.predict_proba

# Оценка модели
baseline_metrics = get_model_metrics(y_test, predictions, X_test, 'baseline', predict_proba)
baseline_metrics

Metrics for baseline:
Accuracy: 0.591
Precision: 0.587
Recall: 0.659
F1 Score: 0.621
ROC-AUC: 0.632

In [ ]:
# Подбор гиперпараметров для логистической регрессии
param_distributions = {
    'model__C': [0.01, 1, 0.1, 100],
    'model__penalty': ['l1', 'none'],
    'model__solver': ['liblinear', 'saga'],
    'model__max_iter': [100, 500, 5000],
    'model__class_weight': [None, 'balanced']
}

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression())
])

f1_scorer = make_scorer(f1_score)

random_search = RandomizedSearchCV(
    pipeline,
    param_distributions,
    n_iter=10,
    cv=3,
    scoring=f1_scorer,
    n_jobs=-1,
    verbose=0,
    random_state=42
)

random_search.fit(X_train, y_train)

print("Best parameters for Logistic Regression:", random_search.best_params_)
print("Best F1 score:", random_search.best_score_)

best_C = random_search.best_params_['model__C']
best_penalty = random_search.best_params_['model__penalty']
best_class_weight = random_search.best_params_['model__class_weight']

Best parameters for Logistic Regression: {'model__solver': 'liblinear', 'model__penalty': 'l1', 'model__max_iter': 100, 'model__class_weight': None, 'model__C': 0.01}
Best F1 score: 0.59927289376972

In [ ]:
best_model = random_search.best_estimator_
predictions = best_model.predict(X_test)
predict_proba = best_model.predict_proba
logistic_metrics = get_model_metrics(y_test, predictions, X_test, 'logistic', predict_proba)
logistic_metrics

Metrics for logistic:
Accuracy: 0.586
Precision: 0.585
Recall: 0.635
F1 Score: 0.609
ROC-AUC: 0.631

In [ ]:
X_train_mean = X_train.loc[:, X_train.columns.str.contains('mean|radiant_win')]
X_test_mean = X_test.loc[:, X_test.columns.str.contains('mean|radiant_win')]

In [ ]:
# Модель на средних
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression())])

param_distributions = {
    'model__C': [0.01, 1, 0.1, 100],
    'model__penalty': ['l1', 'none'],
    'model__solver': ['liblinear', 'saga'],
    'model__max_iter': [100, 500, 5000],
    'model__class_weight': [None, 'balanced']
}

f1_scorer = make_scorer(f1_score)

random_search = RandomizedSearchCV(
    pipeline,
    param_distributions,
    n_iter=10,
    cv=3,
    scoring=f1_scorer,
    n_jobs=-1,
    verbose=0,
    random_state=42
)

random_search.fit(X_train_mean, y_train)

print(f"Лучшие гиперпараметры: {random_search.best_params_}")

Лучшие гиперпараметры: {'model__solver': 'saga', 'model__penalty': 'l1', 'model__max_iter': 100, 'model__class_weight': None, 'model__C': 100}

In [ ]:
best_model = random_search.best_estimator_
predictions = best_model.predict(X_test_mean)
predict_proba = best_model.predict_proba
logistic_mean_metrics = get_model_metrics(y_test, predictions, X_test_mean, 'logistic_mean', predict_proba)
logistic_mean_metrics

Metrics for logistic_mean:
Accuracy: 0.597
Precision: 0.591
Recall: 0.671
F1 Score: 0.629
ROC-AUC: 0.643

Модель только на средних превосходит модель на всех данных по всем метрикам. Это означает, что модель на средних имеет более высокую точность, полноту и сбалансированную метрику F1, что делает ее более эффективной в задаче предсказания победы команды Radiant.

# Другие модели

In [ ]:
# SVM
from sklearn.svm import SVC

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', SVC(probability=True, class_weight='balanced'))
])

pipeline.fit(X_train, y_train)

prediction = pipeline.predict(X_test)
predict_proba = pipeline.predict_proba

In [ ]:
svm_metrics = get_model_metrics(y_test, predictions, X_test, 'svm', predict_proba)
svm_metrics

Metrics for svm:
Accuracy: 0.597
Precision: 0.591
Recall: 0.671
F1 Score: 0.629
ROC-AUC: 0.631

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
# Подбор гиперпараметров LDA
param_distributions = {
    'model__solver': ['lsqr', 'eigen', 'svd'],
    'model__priors': [None, 'uniform', [0.3, 0.7], [0.7, 0.3]],
    'model__n_components': np.arange(1, 4),
}

lda_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LinearDiscriminantAnalysis())
])

f1_scorer = make_scorer(f1_score)

random_search_lda = RandomizedSearchCV(lda_pipeline, param_distributions, n_iter=10, cv=5, scoring=f1_scorer, random_state=42)
random_search_lda.fit(X_train, y_train)

print("Best parameters for LDA:", random_search_lda.best_params_)

Best parameters for LDA: {'model__solver': 'svd', 'model__priors': [0.3, 0.7], 'model__n_components': 1}

In [ ]:
best_model = random_search_lda.best_estimator_
predictions = best_model.predict(X_test)
predict_proba = best_model.predict_proba
LDA_metrics = get_model_metrics(y_test, predictions, X_test, 'LDA', predict_proba)
LDA_metrics

Metrics for LDA:
Accuracy: 0.527
Precision: 0.519
Recall: 0.986
F1 Score: 0.68
ROC-AUC: 0.633

In [ ]:
# Наивный байесовский классификатор
from sklearn.naive_bayes import GaussianNB

nb_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', GaussianNB())
])

nb_pipeline.fit(X_train, y_train)
nb_predictions = nb_pipeline.predict(X_test)
predict_proba = nb_pipeline.predict_proba
nb_metrics = get_model_metrics(y_test, nb_predictions, X_test, 'Naive Bayes', predict_proba)
nb_metrics

Metrics for Naive Bayes:
Accuracy: 0.555
Precision: 0.612
Recall: 0.343
F1 Score: 0.44
ROC-AUC: 0.598

In [ ]:
metrics_df

           Model  Accuracy  Precision  Recall  F1 Score  ROC-AUC
0       baseline     0.591      0.587   0.659     0.621    0.632
1       logistic     0.586      0.585   0.635     0.609    0.631
2  logistic_mean     0.597      0.591   0.671     0.629    0.643
3            svm     0.597      0.591   0.671     0.629    0.631
4            LDA     0.527      0.519   0.986     0.680    0.633
5    Naive Bayes     0.555      0.612   0.343     0.440    0.598

Логистическая регрессия и её модификации, а также LDA, показывают схожие результаты по значениям accuracy, precision, recall и F1 score. Хотя наивный байесовский классификатор показывает хорошую precision, его recall слишком низкий.
Для повышения качества предсказаний, можно попробовать использовать более сложные модели.

In [ ]:
# Дерево решений
from sklearn.tree import DecisionTreeClassifier

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', DecisionTreeClassifier())
])

pipeline.fit(X_train, y_train)

predictions = pipeline.predict(X_test)
predict_proba = pipeline.predict_proba
DT_metrics = get_model_metrics(y_test, predictions, X_test, 'Decision', predict_proba)
DT_metrics

Metrics for Decision:
Accuracy: 0.526
Precision: 0.534
Recall: 0.537
F1 Score: 0.536
ROC-AUC: 0.526

In [ ]:
# Дерево решений
from sklearn.tree import DecisionTreeClassifier

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', DecisionTreeClassifier(class_weight='balanced'))
])

pipeline.fit(X_train, y_train)

predictions = pipeline.predict(X_test)
predict_proba = pipeline.predict_proba
DT_metrics = get_model_metrics(y_test, predictions, X_test, 'Decision', predict_proba)
DT_metrics

Metrics for Decision:
Accuracy: 0.529
Precision: 0.538
Recall: 0.528
F1 Score: 0.533
ROC-AUC: 0.529

Дерево решений в данном случае показывает относительно слабые результаты, модель не очень хорошо отделяет положительный класс от отрицательного, о чем свидетельствует низкий ROC-AUC.

In [ ]:
# Случайный лес
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', RandomForestClassifier(class_weight='balanced'))
])

pipeline.fit(X_train, y_train)

predictions = pipeline.predict(X_test)
predict_proba = pipeline.predict_proba

RT_metrics = get_model_metrics(y_test, predictions, X_test, 'Random Forest', predict_proba)
RT_metrics

Metrics for Random Forest:
Accuracy: 0.581
Precision: 0.586
Recall: 0.602
F1 Score: 0.594
ROC-AUC: 0.615

Random Forest показывает значительное улучшение по сравнению с Decision Tree. Модель достигает лучших результатов по всем метрикам, включая accuracy, precision, recall, F1 score и ROC-AUC.

In [ ]:
pip install catboost

In [ ]:
# catboost
from catboost import CatBoostClassifier
from sklearn.utils.class_weight import compute_class_weight

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', CatBoostClassifier())
])

pipeline.fit(X_train, y_train)

In [ ]:
predictions = pipeline.predict(X_test)
predict_proba = pipeline.predict_proba

catboost_metrics = get_model_metrics(y_test, predictions, X_test, 'CatBoost', predict_proba)
catboost_metrics

Metrics for CatBoost:
Accuracy: 0.599
Precision: 0.605
Recall: 0.613
F1 Score: 0.609
ROC-AUC: 0.647

CatBoost показывает достаточно хорошие результаты по большинству метрик, особенно по recall и F1 Score, что говорит о том, что модель эффективно находит положительные примеры.

In [ ]:
metrics_df

           Model  Accuracy  Precision  Recall  F1 Score  ROC-AUC
0       baseline     0.591      0.587   0.659     0.621    0.632
1       logistic     0.586      0.585   0.635     0.609    0.631
2  logistic_mean     0.597      0.591   0.671     0.629    0.643
3            svm     0.597      0.591   0.671     0.629    0.631
4            LDA     0.527      0.519   0.986     0.680    0.633
5    Naive Bayes     0.555      0.612   0.343     0.440    0.598
6       Decision     0.526      0.534   0.537     0.536    0.526
7       Decision     0.529      0.538   0.528     0.533    0.529
8  Random Forest     0.581      0.586   0.602     0.594    0.615
9       CatBoost     0.599      0.605   0.613     0.609    0.647

CatBoost показал лучшие результаты среди моделей с Accuracy = 0.599, Precision = 0.605, Recall = 0.613, F1 = 0.609 и ROC-AUC = 0.647, что делает его наиболее сбалансированным вариантом. Logistic Mean и SVM также демонстрируют достойные показатели. LDA имеет высокий Recall, но низкую Accuracy. Naive Bayes сильно теряет в Recall, а Decision Trees уступают по всем метрикам.

Для дальнейшего улучшения возможно:

• Подбор гиперпараметров моделей CatBoost и Random Forest.

• Использование других моделей.

• Feature Engineering (добавление информации по героям и тд.)

# Feature Engineering

In [ ]:
# Посчитаем разницу по значениям для команд team_1 team_2
def calculate_team_differences(df):
    """
    Вычисляет разницу между колонками team_1 и team_2 в DataFrame.

    :param df: DataFrame с колонками, содержащими "team_1" и "team_2"
    :return: Новый DataFrame с разницами значений
    """
    diff_columns = {}

    for col in df.columns:
        if "team_1" in col:
            col_team_2 = col.replace("team_1", "team_2")
            if col_team_2 in df.columns:
                new_col_name = col.replace("_team_1", "_diff")
                diff_columns[new_col_name] = df[col] - df[col_team_2]

    return pd.DataFrame(diff_columns)

In [ ]:
X_train_diff = calculate_team_differences(X_train)
X_test_diff = calculate_team_differences(X_test)

In [ ]:
# catboost только на колонках с разницей
from catboost import CatBoostClassifier
from sklearn.utils.class_weight import compute_class_weight

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', CatBoostClassifier())
])

pipeline.fit(X_train_diff, y_train)

In [ ]:
# катбуст показывает хорошие метрики даже только на колонках с разницей
predictions = pipeline.predict(X_test_diff)
predict_proba = pipeline.predict_proba

catboost_metrics = get_model_metrics(y_test, predictions, X_test_diff, 'CatBoost diff', predict_proba)
catboost_metrics

Metrics for CatBoost diff:
Accuracy: 0.596
Precision: 0.599
Recall: 0.622
F1 Score: 0.61
ROC-AUC: 0.638

In [ ]:
# Добавим новые переменные к изначальному датасету
X_train_merge = pd.concat([X_train, X_train_diff], axis=1)
X_test_merge = pd.concat([X_test, X_test_diff], axis=1)

In [ ]:
# catboost
from catboost import CatBoostClassifier
from sklearn.utils.class_weight import compute_class_weight

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', CatBoostClassifier())
])

pipeline.fit(X_train_merge, y_train)

In [ ]:
# Удалось повысить качество предсказания относительно модели без новых колонок
predictions = pipeline.predict(X_test_merge)
predict_proba = pipeline.predict_proba

catboost_metrics = get_model_metrics(y_test, predictions, X_test_merge, 'CatBoost merge', predict_proba)
catboost_metrics

Metrics for CatBoost merge:
Accuracy: 0.592
Precision: 0.597
Recall: 0.614
F1 Score: 0.605
ROC-AUC: 0.649

# Оптимизация гиперпараметров

In [ ]:
!pip install optuna

In [ ]:
import optuna
from catboost import CatBoostClassifier

def objective(trial):
    params = {
        'iterations': trial.suggest_int('iterations', 100, 1000),
        'depth': trial.suggest_int('depth', 3, 10),
        'learning_rate': trial.suggest_loguniform('learning_rate', 1e-5, 0.3),
        'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-5, 10),
        'border_count': trial.suggest_int('border_count', 32, 255),
        'one_hot_max_size': trial.suggest_int('one_hot_max_size', 2, 10),
        'random_state': 42
    }

    model = CatBoostClassifier(**params, verbose=0)

    model.fit(X_train_merge, y_train)

    y_pred_proba = model.predict_proba(X_test_merge)[:, 1]

    roc_auc = roc_auc_score(y_test, y_pred_proba)

    return roc_auc

In [ ]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)

print(f"Лучшие параметры: {study.best_params}")
print(f"Лучший ROC AUC: {study.best_value}")

[I 2025-03-13 11:00:12,836] A new study created in memory with name: no-name-149411d8-5180-4fed-9b8c-eda87af8f718
[I 2025-03-13 11:01:38,293] Trial 0 finished with value: 0.6307323376727909 and parameters: {'iterations': 770, 'depth': 6, 'learning_rate': 0.0001902602200270678, 'l2_leaf_reg': 0.01731516593658743, 'border_count': 201, 'one_hot_max_size': 4}. Best is trial 0 with value: 0.6307323376727909.
[I 2025-03-13 11:02:51,776] Trial 1 finished with value: 0.634906299306569 and parameters: {'iterations': 472, 'depth': 7, 'learning_rate': 0.002146019450775934, 'l2_leaf_reg': 1.0534208458531729, 'border_count': 188, 'one_hot_max_size': 2}. Best is trial 1 with value: 0.634906299306569.
[I 2025-03-13 11:09:06,903] Trial 2 finished with value: 0.6316747054373791 and parameters: {'iterations': 434, 'depth': 10, 'learning_rate': 0.03004936793327931, 'l2_leaf_reg': 0.00021641605283192743, 'border_count': 213, 'one_hot_max_size': 9}. Best is trial 1 with value: 0.634906299306569.
[I 2025-03-13 11:09:44,416] Trial 3 finished with value: 0.6316741486286946 and parameters: {'iterations': 895, 'depth': 3, 'learning_rate': 0.0021944717957690604, 'l2_leaf_reg': 0.8733854636120031, 'border_count': 33, 'one_hot_max_size': 3}. Best is trial 1 with value: 0.634906299306569.
[I 2025-03-13 11:11:24,150] Trial 4 finished with value: 0.6292415752216671 and parameters: {'iterations': 810, 'depth': 6, 'learning_rate': 3.129651555113191e-05, 'l2_leaf_reg': 1.0968432984002263, 'border_count': 252, 'one_hot_max_size': 10}. Best is trial 1 with value: 0.634906299306569.
[I 2025-03-13 11:12:30,490] Trial 5 finished with value: 0.6283852034650081 and parameters: {'iterations': 867, 'depth': 5, 'learning_rate': 1.5535331016784173e-05, 'l2_leaf_reg': 6.962264754625839e-05, 'border_count': 186, 'one_hot_max_size': 10}. Best is trial 1 with value: 0.634906299306569.
[I 2025-03-13 11:14:23,361] Trial 6 finished with value: 0.626403459489477 and parameters: {'iterations': 746, 'depth': 8, 'learning_rate': 0.14783593160129013, 'l2_leaf_reg': 2.0335079260167235, 'border_count': 91, 'one_hot_max_size': 10}. Best is trial 1 with value: 0.634906299306569.
[I 2025-03-13 11:15:32,878] Trial 7 finished with value: 0.6306663249098697 and parameters: {'iterations': 643, 'depth': 6, 'learning_rate': 0.0001629678545510167, 'l2_leaf_reg': 0.006373829427341873, 'border_count': 193, 'one_hot_max_size': 8}. Best is trial 1 with value: 0.634906299306569.
[I 2025-03-13 11:15:38,645] Trial 8 finished with value: 0.626791431407264 and parameters: {'iterations': 113, 'depth': 3, 'learning_rate': 0.00011441833203419956, 'l2_leaf_reg': 0.0003835544748260235, 'border_count': 209, 'one_hot_max_size': 7}. Best is trial 1 with value: 0.634906299306569.
[I 2025-03-13 11:17:07,218] Trial 9 finished with value: 0.6335247332252258 and parameters: {'iterations': 465, 'depth': 7, 'learning_rate': 0.0014110576109575195, 'l2_leaf_reg': 2.5653709892614954e-05, 'border_count': 255, 'one_hot_max_size': 8}. Best is trial 1 with value: 0.634906299306569.
[I 2025-03-13 11:18:31,814] Trial 10 finished with value: 0.6371084776535043 and parameters: {'iterations': 260, 'depth': 9, 'learning_rate': 0.005036644444753628, 'l2_leaf_reg': 0.07844103083956507, 'border_count': 135, 'one_hot_max_size': 2}. Best is trial 10 with value: 0.6371084776535043.
[I 2025-03-13 11:19:51,699] Trial 11 finished with value: 0.6367331267325643 and parameters: {'iterations': 253, 'depth': 9, 'learning_rate': 0.004858834869816605, 'l2_leaf_reg': 0.06909966563164276, 'border_count': 129, 'one_hot_max_size': 2}. Best is trial 10 with value: 0.6371084776535043.
[I 2025-03-13 11:21:53,714] Trial 12 finished with value: 0.6401867016639485 and parameters: {'iterations': 212, 'depth': 10, 'learning_rate': 0.014313052854560394, 'l2_leaf_reg': 0.0505548476584956, 'border_count': 123, 'one_hot_max_size': 5}. Best is trial 12 with value: 0.6401867016639485.
[I 2025-03-13 11:24:33,789] Trial 13 finished with value: 0.6389376560495005 and parameters: {'iterations': 279, 'depth': 10, 'learning_rate': 0.022958824750862437, 'l2_leaf_reg': 0.0700859924380184, 'border_count': 122, 'one_hot_max_size': 5}. Best is trial 12 with value: 0.6401867016639485.
[I 2025-03-13 11:26:36,238] Trial 14 finished with value: 0.6328898475897082 and parameters: {'iterations': 246, 'depth': 10, 'learning_rate': 0.030672881844243462, 'l2_leaf_reg': 0.0023686070673026144, 'border_count': 97, 'one_hot_max_size': 5}. Best is trial 12 with value: 0.6401867016639485.
[I 2025-03-13 11:27:02,931] Trial 15 finished with value: 0.6139283465176351 and parameters: {'iterations': 106, 'depth': 9, 'learning_rate': 0.20931374204235262, 'l2_leaf_reg': 0.11770940821820554, 'border_count': 90, 'one_hot_max_size': 6}. Best is trial 12 with value: 0.6401867016639485.
[I 2025-03-13 11:31:12,534] Trial 16 finished with value: 0.6366291272438385 and parameters: {'iterations': 363, 'depth': 10, 'learning_rate': 0.024375969475021266, 'l2_leaf_reg': 0.0020508482533206315, 'border_count': 159, 'one_hot_max_size': 5}. Best is trial 12 with value: 0.6401867016639485.
[I 2025-03-13 11:32:23,214] Trial 17 finished with value: 0.6362842151976476 and parameters: {'iterations': 581, 'depth': 8, 'learning_rate': 0.07394127670364785, 'l2_leaf_reg': 0.23053435064803393, 'border_count': 56, 'one_hot_max_size': 5}. Best is trial 12 with value: 0.6401867016639485.
[I 2025-03-13 11:33:33,678] Trial 18 finished with value: 0.6401131410499717 and parameters: {'iterations': 332, 'depth': 8, 'learning_rate': 0.010082372401253661, 'l2_leaf_reg': 0.023392963134430376, 'border_count': 156, 'one_hot_max_size': 4}. Best is trial 12 with value: 0.6401867016639485.
[I 2025-03-13 11:34:53,626] Trial 19 finished with value: 0.6337580360640036 and parameters: {'iterations': 360, 'depth': 8, 'learning_rate': 0.0006298431237322446, 'l2_leaf_reg': 9.858370461638774, 'border_count': 161, 'one_hot_max_size': 4}. Best is trial 12 with value: 0.6401867016639485.
[I 2025-03-13 11:35:04,736] Trial 20 finished with value: 0.6318213935919116 and parameters: {'iterations': 179, 'depth': 4, 'learning_rate': 0.0077435250074502264, 'l2_leaf_reg': 0.015362722892311819, 'border_count': 159, 'one_hot_max_size': 6}. Best is trial 12 with value: 0.6401867016639485.
[I 2025-03-13 11:36:36,755] Trial 21 finished with value: 0.6360223913807006 and parameters: {'iterations': 325, 'depth': 9, 'learning_rate': 0.01210291042963684, 'l2_leaf_reg': 0.03186363878124601, 'border_count': 113, 'one_hot_max_size': 4}. Best is trial 12 with value: 0.6401867016639485.
[I 2025-03-13 11:38:21,415] Trial 22 finished with value: 0.636643728004897 and parameters: {'iterations': 188, 'depth': 10, 'learning_rate': 0.06179157542575904, 'l2_leaf_reg': 0.3190475745542736, 'border_count': 117, 'one_hot_max_size': 3}. Best is trial 12 with value: 0.6401867016639485.
[I 2025-03-13 11:39:00,556] Trial 23 finished with value: 0.6385449203240801 and parameters: {'iterations': 307, 'depth': 8, 'learning_rate': 0.011570874781877075, 'l2_leaf_reg': 0.004325623877336252, 'border_count': 62, 'one_hot_max_size': 7}. Best is trial 12 with value: 0.6401867016639485.
[I 2025-03-13 11:41:22,475] Trial 24 finished with value: 0.6154318537008692 and parameters: {'iterations': 419, 'depth': 9, 'learning_rate': 0.07447622797553823, 'l2_leaf_reg': 0.0011541753351366575, 'border_count': 144, 'one_hot_max_size': 5}. Best is trial 12 with value: 0.6401867016639485.
[I 2025-03-13 11:46:12,779] Trial 25 finished with value: 0.6432789696267669 and parameters: {'iterations': 554, 'depth': 10, 'learning_rate': 0.019724187092039273, 'l2_leaf_reg': 0.0340183337298803, 'border_count': 108, 'one_hot_max_size': 3}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 11:47:51,094] Trial 26 finished with value: 0.6344025730500513 and parameters: {'iterations': 990, 'depth': 7, 'learning_rate': 0.0008009266012060697, 'l2_leaf_reg': 0.0239255281212332, 'border_count': 75, 'one_hot_max_size': 3}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 11:50:20,691] Trial 27 finished with value: 0.6400014081072953 and parameters: {'iterations': 561, 'depth': 9, 'learning_rate': 0.003925376266406584, 'l2_leaf_reg': 0.0075124301360712815, 'border_count': 105, 'one_hot_max_size': 4}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 11:58:08,951] Trial 28 finished with value: 0.6395596732176445 and parameters: {'iterations': 652, 'depth': 10, 'learning_rate': 0.01728322799481566, 'l2_leaf_reg': 0.30302093103009126, 'border_count': 172, 'one_hot_max_size': 3}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 11:58:45,554] Trial 29 finished with value: 0.6296532424423584 and parameters: {'iterations': 518, 'depth': 5, 'learning_rate': 0.0005348498192747104, 'l2_leaf_reg': 0.029846091796858126, 'border_count': 144, 'one_hot_max_size': 4}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 12:01:49,934] Trial 30 finished with value: 0.6264832687342458 and parameters: {'iterations': 649, 'depth': 8, 'learning_rate': 0.0619747110681983, 'l2_leaf_reg': 0.0010895304726066327, 'border_count': 234, 'one_hot_max_size': 3}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 12:04:18,554] Trial 31 finished with value: 0.6402806785963545 and parameters: {'iterations': 561, 'depth': 9, 'learning_rate': 0.0040656614253248785, 'l2_leaf_reg': 0.009464221258493872, 'border_count': 104, 'one_hot_max_size': 4}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 12:07:32,102] Trial 32 finished with value: 0.6419657054107142 and parameters: {'iterations': 600, 'depth': 9, 'learning_rate': 0.008121596313036985, 'l2_leaf_reg': 0.011980316067929857, 'border_count': 137, 'one_hot_max_size': 4}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 12:12:04,772] Trial 33 finished with value: 0.6381692600649821 and parameters: {'iterations': 518, 'depth': 10, 'learning_rate': 0.0030126415220514216, 'l2_leaf_reg': 0.012127552543216324, 'border_count': 107, 'one_hot_max_size': 2}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 12:14:44,093] Trial 34 finished with value: 0.63654894679328 and parameters: {'iterations': 714, 'depth': 9, 'learning_rate': 0.0014188813590385026, 'l2_leaf_reg': 0.0004755488239372396, 'border_count': 80, 'one_hot_max_size': 6}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 12:20:36,055] Trial 35 finished with value: 0.640605669265169 and parameters: {'iterations': 602, 'depth': 10, 'learning_rate': 0.006571810958490513, 'l2_leaf_reg': 0.003586018237621691, 'border_count': 127, 'one_hot_max_size': 3}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 12:21:50,365] Trial 36 finished with value: 0.6393624392080919 and parameters: {'iterations': 584, 'depth': 7, 'learning_rate': 0.006691151409210956, 'l2_leaf_reg': 0.00415841567685789, 'border_count': 137, 'one_hot_max_size': 3}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 12:23:32,510] Trial 37 finished with value: 0.6394853083244569 and parameters: {'iterations': 704, 'depth': 9, 'learning_rate': 0.0025284803717786205, 'l2_leaf_reg': 0.002225160677551428, 'border_count': 35, 'one_hot_max_size': 2}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 12:32:57,672] Trial 38 finished with value: 0.6353472299170089 and parameters: {'iterations': 779, 'depth': 10, 'learning_rate': 0.0003027995965150801, 'l2_leaf_reg': 0.00016598911104181343, 'border_count': 175, 'one_hot_max_size': 3}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 12:35:09,948] Trial 39 finished with value: 0.6360321664664939 and parameters: {'iterations': 509, 'depth': 9, 'learning_rate': 0.0016111031950083337, 'l2_leaf_reg': 0.010217152911140613, 'border_count': 99, 'one_hot_max_size': 2}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 12:39:40,281] Trial 40 finished with value: 0.6354321123075692 and parameters: {'iterations': 615, 'depth': 10, 'learning_rate': 6.698236371787253e-05, 'l2_leaf_reg': 0.000609869656751959, 'border_count': 79, 'one_hot_max_size': 4}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 12:43:48,899] Trial 41 finished with value: 0.6417114294448227 and parameters: {'iterations': 435, 'depth': 10, 'learning_rate': 0.01633483204738849, 'l2_leaf_reg': 0.037540922641015266, 'border_count': 124, 'one_hot_max_size': 3}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 12:48:08,185] Trial 42 finished with value: 0.634454789331125 and parameters: {'iterations': 433, 'depth': 10, 'learning_rate': 0.03710108336528909, 'l2_leaf_reg': 0.15777677945543522, 'border_count': 132, 'one_hot_max_size': 3}. Best is trial 25 with value: 0.6432789696267669.
[I 2025-03-13 12:50:55,502] Trial 43 finished with value: 0.6433634189439059 and parameters: {'iterations': 492, 'depth': 9, 'learning_rate': 0.04002779912137227, 'l2_leaf_reg': 0.6897124695938294, 'border_count': 148, 'one_hot_max_size': 4}. Best is trial 43 with value: 0.6433634189439059.
[I 2025-03-13 12:56:04,189] Trial 44 finished with value: 0.6176843304322983 and parameters: {'iterations': 484, 'depth': 10, 'learning_rate': 0.11579369257551464, 'l2_leaf_reg': 0.6492025236566712, 'border_count': 148, 'one_hot_max_size': 3}. Best is trial 43 with value: 0.6433634189439059.
[I 2025-03-13 12:58:05,618] Trial 45 finished with value: 0.6426083245001822 and parameters: {'iterations': 401, 'depth': 9, 'learning_rate': 0.043058943217276345, 'l2_leaf_reg': 3.074331987548903, 'border_count': 127, 'one_hot_max_size': 2}. Best is trial 43 with value: 0.6433634189439059.
[I 2025-03-13 12:58:46,356] Trial 46 finished with value: 0.6462947691969229 and parameters: {'iterations': 416, 'depth': 6, 'learning_rate': 0.04377496768210657, 'l2_leaf_reg': 2.5606882081618374, 'border_count': 170, 'one_hot_max_size': 2}. Best is trial 46 with value: 0.6462947691969229.
[I 2025-03-13 12:59:15,903] Trial 47 finished with value: 0.6436864917161408 and parameters: {'iterations': 410, 'depth': 5, 'learning_rate': 0.03850371068042437, 'l2_leaf_reg': 4.011150669932792, 'border_count': 179, 'one_hot_max_size': 2}. Best is trial 46 with value: 0.6462947691969229.
[I 2025-03-13 12:59:45,249] Trial 48 finished with value: 0.628996146327095 and parameters: {'iterations': 392, 'depth': 5, 'learning_rate': 0.2932982735487889, 'l2_leaf_reg': 4.763982640959998, 'border_count': 196, 'one_hot_max_size': 2}. Best is trial 46 with value: 0.6462947691969229.
[I 2025-03-13 13:00:35,525] Trial 49 finished with value: 0.6467783266055377 and parameters: {'iterations': 468, 'depth': 6, 'learning_rate': 0.03828694027547689, 'l2_leaf_reg': 1.7598081363931177, 'border_count': 207, 'one_hot_max_size': 2}. Best is trial 49 with value: 0.6467783266055377.

Лучшие параметры: {'iterations': 468, 'depth': 6, 'learning_rate': 0.03828694027547689, 'l2_leaf_reg': 1.7598081363931177, 'border_count': 207, 'one_hot_max_size': 2}
Лучший ROC AUC: 0.6467783266055377

In [ ]:
best_params = study.best_params
best_model = CatBoostClassifier(**best_params)
best_model.fit(X_train_merge, y_train)

# Оценка на тестовой выборке
y_pred_proba_best = best_model.predict_proba(X_test_merge)[:, 1]  # Получаем вероятности для положительного класса
best_roc_auc = roc_auc_score(y_test, y_pred_proba_best)
print(f"ROC AUC с лучшими гиперпараметрами: {best_roc_auc}")

In [ ]:
best_params

{'iterations': 468,
 'depth': 6,
 'learning_rate': 0.03828694027547689,
 'l2_leaf_reg': 1.7598081363931177,
 'border_count': 207,
 'one_hot_max_size': 2}

In [ ]:
predictions = best_model.predict(X_test_merge)
y_pred_proba_best = best_model.predict_proba
catboost_metrics = get_model_metrics(y_test, predictions, X_test_merge, 'CatBoost optuna', y_pred_proba_best)
catboost_metrics

Metrics for CatBoost optuna:
Accuracy: 0.592
Precision: 0.592
Recall: 0.638
F1 Score: 0.614
ROC-AUC: 0.645

Подбор гиперпараметров не улучшил качество модели, метрика Accuracy отсалась прежней, f1 увеличился, ROC-AUC снизился

# lightgbm

In [ ]:
!pip install lightgbm

In [ ]:
from lightgbm import LGBMClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

pipeline = Pipeline([
    ('model', LGBMClassifier(random_state=42))
])

pipeline.fit(X_train_merge, y_train)

In [ ]:
predictions = pipeline.predict(X_test_merge)
predict_proba = pipeline.predict_proba

catboost_metrics = get_model_metrics(y_test, predictions, X_test_merge, 'LGBMClassifier', predict_proba)
catboost_metrics

Metrics for LGBMClassifier:
Accuracy: 0.589
Precision: 0.592
Recall: 0.618
F1 Score: 0.605
ROC-AUC: 0.64

# Методы снижения размерности

In [ ]:
# Снижение размерности PCA
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=270)
X_reduced = svd.fit_transform(X_train_merge)

explained_variance = np.cumsum(svd.explained_variance_ratio_)

n_components = np.argmax(explained_variance >= 0.95) + 1

print(f"Достаточно оставить {n_components} компонент для 95% дисперсии.")

Достаточно оставить 9 компонент для 95% дисперсии.

In [ ]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_merge)
X_test_scaled = scaler.transform(X_test_merge)

pca = PCA(n_components=0.99)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

print("Размерности после PCA:")
print("X_train:", X_train_pca.shape)
print("X_test:", X_test_pca.shape)

Размерности после PCA:
X_train: (44330, 109)
X_test: (8042, 109)

In [ ]:
from catboost import CatBoostClassifier
from sklearn.utils.class_weight import compute_class_weight

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', CatBoostClassifier())
])

pipeline.fit(X_train_pca, y_train)

In [ ]:
# качество модели не улучшилось
predictions = pipeline.predict(X_test_pca)
predict_proba = pipeline.predict_proba

catboost_metrics = get_model_metrics(y_test, predictions, X_test_pca, 'CatBoost pca', predict_proba)
catboost_metrics

Metrics for CatBoost pca:
Accuracy: 0.58
Precision: 0.589
Recall: 0.575
F1 Score: 0.582
ROC-AUC: 0.626

In [ ]:
# Снижение размерности LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_merge)
X_test_scaled = scaler.transform(X_test_merge)
lda = LinearDiscriminantAnalysis(n_components=1)
X_train_lda = lda.fit_transform(X_train_scaled, y_train)
X_test_lda = lda.transform(X_test_scaled)

In [ ]:
# catboost
from catboost import CatBoostClassifier
from sklearn.utils.class_weight import compute_class_weight

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', CatBoostClassifier())
])

pipeline.fit(X_train_lda, y_train)

In [ ]:
predictions = pipeline.predict(X_test_lda)
predict_proba = pipeline.predict_proba

catboost_metrics = get_model_metrics(y_test, predictions, X_test_lda, 'CatBoost lda', predict_proba)
catboost_metrics

Metrics for CatBoost lda:
Accuracy: 0.588
Precision: 0.583
Recall: 0.661
F1 Score: 0.62
ROC-AUC: 0.631

# Отбор признаков

In [ ]:
pip install autofeat

In [ ]:
# Отбор на датасете с изначальными признаками
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# feature selection
from autofeat import FeatureSelector
fsel = FeatureSelector(verbose=1)
X_train_selected = fsel.fit_transform(X_train, y_train)
X_test_selected = fsel.transform(X_test)

[featsel] Scaling data...done.

In [ ]:
# catboost
from catboost import CatBoostClassifier
from sklearn.utils.class_weight import compute_class_weight

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', CatBoostClassifier())
])

pipeline.fit(X_train_selected, y_train)

In [ ]:
# Качество на уровне лучшей модели с дополнительными признаками
predictions = pipeline.predict(X_test_selected)
predict_proba = pipeline.predict_proba

catboost_metrics = get_model_metrics(y_test, predictions, X_test_selected, 'CatBoost select', predict_proba)
catboost_metrics

Metrics for CatBoost select:
Accuracy: 0.593
Precision: 0.596
Recall: 0.619
F1 Score: 0.607
ROC-AUC: 0.648

# Рассмотрим данные с признаками героев

In [ ]:
y_train_heroes = pd.read_csv('y_train_heroes.csv', index_col=0)
X_train_heroes = pd.read_csv('X_train_heroes.csv', index_col=0)
X_test_heroes = pd.read_csv('X_test_heroes.csv', index_col=0)
y_test_heroes = pd.read_csv('y_test_heroes.csv', index_col=0)

In [ ]:
X_train_heroes.head()

,previous_kills_avr_heroes_team_1_mean,previous_hero_kills_avr_heroes_team_1_mean,previous_courier_kills_avr_heroes_team_1_mean,previous_observer_kills_avr_heroes_team_1_mean,previous_kills_per_min_avr_heroes_team_1_mean,previous_kda_avr_heroes_team_1_mean,previous_denies_avr_heroes_team_1_mean,previous_hero_healing_avr_heroes_team_1_mean,previous_assists_avr_heroes_team_1_mean,previous_hero_damage_avr_heroes_team_1_mean,...,previous_tower_kills_avr_players_team_2_min,previous_win_avr_players_team_2_mean,previous_win_avr_players_team_2_max,previous_win_avr_players_team_2_min,previous_duration_avr_players_team_2_mean,previous_duration_avr_players_team_2_max,previous_duration_avr_players_team_2_min,previous_first_blood_time_avr_players_team_2_mean,previous_first_blood_time_avr_players_team_2_max,previous_first_blood_time_avr_players_team_2_min
match_id,,,,,,,,,,,,,,,,,,,,,
6947109699,5.500000,5.500000,0.000000,0.750000,0.169753,6.402500,5.500000,1688.000000,17.000000,12758.000000,...,0.0,0.0,0.0,0.0,32.400000,32.400000,32.400000,2.066667,2.066667,2.066667
6947952638,7.833333,7.666667,0.000000,1.666667,0.273104,5.216667,7.500000,2389.000000,14.666667,16532.833333,...,0.0,0.2,1.0,0.0,29.450000,29.450000,29.450000,1.750000,1.750000,1.750000
6948030779,4.708333,4.583333,0.583333,0.583333,0.161977,1.983333,4.875000,53.000000,8.750000,13105.666667,...,0.0,1.0,1.0,1.0,27.416667,27.416667,27.416667,2.516667,2.516667,2.516667
6948105554,3.777778,3.777778,0.666667,0.888889,0.115479,8.942222,4.111111,1919.777778,12.000000,10617.555556,...,0.0,0.5,0.5,0.5,29.958333,29.958333,29.958333,1.258333,1.258333,1.258333
6948219195,6.333333,6.000000,0.000000,0.500000,0.213535,4.648333,8.500000,198.833333,12.833333,15254.333333,...,0.0,1.0,1.0,1.0,29.316667,29.316667,29.316667,4.000000,4.000000,4.000000

In [ ]:
from catboost import CatBoostClassifier
from sklearn.utils.class_weight import compute_class_weight

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', CatBoostClassifier())
])

pipeline.fit(X_train_heroes, y_train_heroes)

In [ ]:
# Лучшее качество по ROC-AUC среди всех моделей
predictions = pipeline.predict(X_test_heroes)
predict_proba = pipeline.predict_proba

catboost_metrics = get_model_metrics(y_test_heroes, predictions, X_test_heroes, 'CatBoost heroes', predict_proba)
catboost_metrics

Metrics for CatBoost heroes:
Accuracy: 0.598
Precision: 0.604
Recall: 0.611
F1 Score: 0.607
ROC-AUC: 0.65

In [ ]:
# переменные с разницей по командам
X_train_diff_heroes = calculate_team_differences(X_train_heroes)
X_test_diff_heroes = calculate_team_differences(X_test_heroes)

In [ ]:
X_train_merge_heroes = pd.concat([X_train_heroes, X_train_diff_heroes], axis=1)
X_test_merge_heroes = pd.concat([X_test_heroes, X_test_diff_heroes], axis=1)

In [ ]:
# catboost
from catboost import CatBoostClassifier
from sklearn.utils.class_weight import compute_class_weight

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', CatBoostClassifier())
])

pipeline.fit(X_train_merge_heroes, y_train_heroes)

In [ ]:
# лучшее качество по метрикам ROC-AUC и Accuracy
predictions = pipeline.predict(X_test_merge_heroes)
predict_proba = pipeline.predict_proba

catboost_metrics = get_model_metrics(y_test_heroes, predictions, X_test_merge_heroes, 'CatBoost heroes diff', predict_proba)
catboost_metrics

Metrics for CatBoost heroes diff:
Accuracy: 0.606
Precision: 0.611
Recall: 0.622
F1 Score: 0.616
ROC-AUC: 0.655